# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'company_salary_companies',
            },
        ),
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('date_period', models.DateTimeField(db_index=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='employeeInfo', related_query_name='employeeInfo', to='company_salary.Company')),
            ],
            options={
                'db_table': 'company_salary_employee_info',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employed_average', models.DecimalField(decimal_places=4, max_digits=14)),
                ('copyright_average', models.DecimalField(decimal_places=4, max_digits=14)),
                ('total_ssi', models.DecimalField(decimal_places=4, max_digits=14)),
                ('date_period', models.DateTimeField(db_index=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='salaries', related_query_name='salary', to='company_salary.Company')),
            ],
            options={
                'db_table': 'company_salary_salaries',
            },
        ),
    ]
